require("core.options")
require("core.lazy")
require("core.ui")
require("core.keymaps")
local icon, color = require("nvim-web-devicons").get_icon_color("init.lua", "lua")
assert(icon == "󰢱")
assert(color == "#7DCFFF")
